### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by Spawnkid** [pro-celigo/lib-netsuite-servicemgr#4] opened 2018-04-09 09:02 UTC
I was trying to do a simple test using the following:

            var config = new NetSuiteConfiguration();
            var factory = new ClientFactory(config.ApplicationId);
            _client = factory.CreateClient(config.PassportProvider);
           
           var serverTimeResult = await _client.getServerTimeAsync();

Both ApplicationId and PassportProvider (where email,password,account and role) are all set but end up getting an exception below:

Message
InvalidOperationException: Instance validation error: '
                        USER_ERROR
                    ' is not a valid value for FaultCodeType.

Stack
					   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.ServiceModel.Dispatcher.XmlSerializerObjectSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlReader reader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at System.ServiceModel.Dispatcher.XmlSerializerFaultFormatter.CreateFaultException(MessageFault messageFault, String action)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SuiteTalk.NetSuitePortTypeClient.<getServerTimeAsync>d__164.MoveNext() in F:\VS 2017 Test Projects\PaypalNetsuite\3rdParty\SuiteTalk-2017.2\SuiteTalk\INetSuiteClient.gen.cs:line 482
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PaypalNetsuite.Services.JCurveService.<Test>d__4.MoveNext() in F:\VS 2017 Test Projects\PaypalNetsuite\PaypalNetsuite\Services\JCurveService.cs:line 23

**Comment by sameera** [comment] 2018-05-22 01:46
@Spawnkid Sorry for missing this message.
Do you continue to get this error with the latest version of the library? 
First glance, it does look like your request went through but you got a non SOAP/XML response which failed on deserialization. Can you check whether the request gets registered on the WebService Usage Log on NetSuite?

**Comment by sameera** [comment] 2018-09-28 01:28
Closing as no response has been received.

**Comment by dzungmeister** [comment] 2019-02-04 11:33
Hi @Spawnkid 

How did you resolved this issue? I am facing same challenge in  my project.

**Comment by sameera** [comment] 2019-02-06 07:12
Hi @dzungmeister 
Can you switch to the 2018.2 branch and see if the issue is resolved in that branch?

**Comment by dantheman999301** [comment] 2019-02-14 07:47
The branch won't fix it, the issue is firstly with how dotnet serialises the XML sent back from NetSuite (there are spaces and new lines in the error) and then the error itself.

It's likely this error is due to not getting / setting the data centre url first before making the request 👍

**Comment by sameera** [comment] 2019-02-15 17:55
Sorry about that @dantheman999301 
Internally, we have library wrapped in a REST API that takes care of some shared concerns like Data Center, concurrency management and resilience. But, we should have paid attention that the samples are broken with NetSuite's new account specific URL format. We'll update the samples in the coming days.

In the meantime, please use the `CreateClient(ITokenPassportProvider tokenPassportProvider, IConfigurationProvider configProvider)` overload of the `ClientFactory` to pass in the DataCenterURL.

**Comment by dmelinosky** [comment] 2019-02-15 20:07
I can confirm that the workaround does work.  Thanks for posting that, really helped me out.

**Comment by efeker** [comment] 2019-09-02 19:32
I see that we need to use the overloaded method, however I am not sure what DataCenterURL should be passed to the config provider. Can anyone point out, please?

**Comment by sameera** [comment] 2019-09-03 03:30
@efeker `https://<your-account-number>.suitetalk.api.netsuite.com` should work.
Note that if you are using a sandbox or RP account (where you would have a `_SB` or similar in the account number), you will need to replace `_` with `-`.

**Closed** 2019-09-10 01:01 UTC
Labels: question

**Comment by camerontbelt** [comment] 2019-10-07 15:20
I am getting this same error message when trying to login. Has a fix been pushed out for this or are we still supposed to use the work around?

**Comment by sameera** [comment] 2019-10-07 15:29
There is a fix done. Do you have some code you can share for me to take a look?

**Comment by camerontbelt** [comment] 2019-10-07 16:07
`
        public NetsuiteCredentials(string account, string email, string password, string role)
        {
            Account = account;
            UserName = email;
            Password = password;
            Role = role;

            var recordRef = new RecordRef
            {
                internalId = Constants.InternalId
            };

            _passport.role = recordRef;
            _passport = new Passport
            {
                account = Account,
                email = UserName,
                password = Password,
                role = recordRef
            };
            _passportProvider = new PassportProvider(_passport);

            var factory = new ClientFactory(Constants.ApplicationId);
            _netSuite = factory.CreateClient(_passportProvider);
        }

        public async Task<SessionResponse> Login()
        {
            var login = await _netSuite.loginAsync();
            IsSuccess = login.status.isSuccess;
            return login;
        }`

**Comment by camerontbelt** [comment] 2019-10-07 16:12
@sameera When I tried to get the server time I receive this error 
`System.AggregateException: 'Deploy_cbelt 2019-10-07 11:11:05iguration' was not found.  The settings can not be )'`

**Comment by sameera** [comment] 2019-10-07 16:48
I'm not quite sure of the state of `loginAsync()` as we exclusively work with request level authentication. Your first code block looks fine other than calling loginAsync. 

Can you skip the explicit login and try getServerTime directly? Also, were you able to run the unit tests in the solution?

**Comment by camerontbelt** [comment] 2019-10-07 16:56
@sameera How else am I supposed to login? Whats the best method to do that?

**Comment by sameera** [comment] 2019-10-07 17:32
SuiteTalk supports what's called request-level authentication. Rather than doing an explicit login call, you send the the credentials on each request. This is the recommended approach as this makes your communications with NetSuite, stateless.

You don't need to do anything special to achieve this with this library. Once you've provided the passport provider and created the client, that client is automatically configured to send request-level auth headers. So, rathe than calling `loginAsync` and then calling your WS methods (such as `getServerTimeAsync`), call that WS method directly, Yoiu can see this in the unit tests where we don't make any calls to login.

**Comment by camerontbelt** [comment] 2019-10-07 17:57
So to get serverTime I still have to provide a passport, token passport, application info, and partner info. I have no idea what token passport or partner info is.

**Comment by camerontbelt** [comment] 2019-10-07 18:25
@sameera Ok I got the code from your site working, it gives me back the correct server time with no errors. 

My next question is How do I create and post an invoice to netsuite?

Can I run reports at netsuite and get back the data?

**Comment by sameera** [comment] 2019-10-14 04:46
@camerontbelt 
Create an object of `SuiteTalk.Invoice` record type. Set the properties you want and call the `addAsync` method (or `addListAsync` method if you have multiple records).

In terms of reports, there are a few reports that you can run. This is exposed through the `getPostingTransactionSummaryAsync` function. I haven't used this function much  and don't really have examples that I could share.

**Comment by MaggieLee732** [comment] 2020-03-13 19:19
I'm getting the same "Instance validation error: ' USER_ERROR ' is not a valid value for FaultCodeType." when trying to use `loginAsync` with a production account. The log in works when using a sandbox account ID with the "_SB1" at the end. But when I try to use a production account ID without the "_SB1" it fails. 

Is there a solution to this?

**Comment by sameera** [comment] 2020-03-14 11:46
@MaggieLee732 is there a specific reason you want to use `loginAsync`? The Service Manager uses request-level authentication which is the recommended approach for calling SuiteTalk WS. To use `loginAsync` would mean meantaining session cookie and the library does not support that.

Instead, simply provide a passport provider when you call `CreateClient` and the library will take care of passing the credentials on each request.

**Comment by MaggieLee732** [comment] 2020-03-14 17:22
@sameera I have to use `loginAsync` as well as other async methods (`getAsync`, `searchAsync`, ect.) because the nuget library I'm using only has `INetSuiteClient` and that client only allows for async methods. I don't understand why it works perfectly when using a sandbox account ID.

**Comment by sameera** [comment] 2020-03-16 18:17
@MaggieLee732 from the error you are seeing, it looks like NetSuite is sending back a non-standard response to your request. The actual reason for the failure might be masked by this parser error.
Are you on a Windows environment? If so, can you use Fiddler to take a look at the response sent back by NetSuite?
Another option is, if you have access, is to take a look at the NetSuite account's Login Audit Trail. It might log some information that would help you see the root cause.

**Comment by sameera** [comment] 2020-08-25 05:35
@benwmills 
You can follow how we construct the Account Specific URL here:
https://github.com/pro-celigo/lib-netsuite-servicemgr/blob/master/Celigo.ServiceManager.NetSuite/src/ClientFactoryBase.cs#L92

**Comment by benwmills** [comment] 2020-09-02 17:22
I couldn't get this working, but I ended up using an account specific WSDL:

https://123456.suitetalk.api.netsuite.com/wsdl/v2017_2_0/netsuite.wsdl

where 123456 is replaced with your account ID.  That way, you don't even have to call getDataCenterUrls.

I outlined all the changes I had to make here:

https://medium.com/@benwmills/using-the-netsuite-suitetalk-api-with-net-core-net-standard-40f1a4464da1
